- name: Deleting previous .zip files
  ansible.builtin.shell: find "{{ local_path }}" -type f -name "*.zip" -exec rm -f {} \;
  delegate_to: localhost

- name: Compressing static-files
  ansible.builtin.archive:
    path: "{{ local_path }}/*"
    dest: "{{ local_path }}/static.zip"
    format: zip
  register: compress_result
  delegate_to: localhost

- name: Verificar ruta en el contenedor ansible
  command: ls -la "{{ local_path }}"
  delegate_to: localhost

- name: Checking if the file compression has been performed correctly
  debug:
    msg: Properly compressed files
  failed_when: compress_result.changed == false

- name: ensure remote_path production server exits
  ansible.builtin.file:
    path: "{{ remote_temp_path }}"
    state: directory

- name: Copying static zip to production server
  ansible.builtin.copy:
    src:  "{{ local_path }}/static.zip"
    dest: "{{ remote_temp_path }}/static.zip"

- name: unzip files
  ansible.builtin.unarchive: 
    src: "{{ remote_temp_path }}/static.zip"
    dest: "{{ remote_temp_path }}"
    remote_src: yes

- name: Delete zip file
  ansible.builtin.file:
    path: "{{ remote_temp_path }}/static.zip"
    state: absent

- name: Moving static files to nginx
  ansible.builtin.copy:
    src: "{{ remote_temp_path }}/"
    dest: "{{ remote_path }}/"
    remote_src: yes

- name: Deleting remote temp path
  ansible.builtin.file:
    path: "{{ remote_temp_path }}"
    state: absent

- name: Ensure nginx is running
  ansible.builtin.service:
    name: nginx
    state: started

- name: Check site
  ansible.builtin.uri:
    url: "http://{{ web_host }}:{{ web_port }}"
    return_content: yes
  register: result
  failed_when: result.status != 200





